ewz_recaptcha:
    version: 3
    enabled: true
    hide_badge: true
    score_threshold: 0.6
    public_key:  '%env(EWZ_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(EWZ_RECAPTCHA_SECRET)%'

when@dev:
    ewz_recaptcha:
        enabled: false
