fos_ck_editor:
    default_config: 'app_custom_config'
    configs:
        app_custom_config:
            height: '450px'
            toolbar:
                - [ 'Undo', 'Redo', '-', 'Cut', 'Copy', 'Paste', '-', 'Bold', 'Italic', 'Underline', 'Strike', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Subscript', 'Superscript', '-', 'Alignment', '-', 'BulletedList', 'NumberedList', 'Indent', 'Outdent', '-', 'Blockquote', '-', 'Link', 'Unlink', '-', 'Source' ]
            versionCheck: false
            autoParagraph: false
            extraPlugins:
                - 'justify'
        app_custom_config_small:
            height: '200px'
            toolbar:
                - [ 'Undo', 'Redo', '-', 'Cut', 'Copy', 'Paste', '-', 'Bold', 'Italic', 'Underline', 'Strike', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Subscript', 'Superscript', '-', 'Alignment', '-', 'BulletedList', 'NumberedList', 'Indent', 'Outdent', '-', 'Blockquote', '-', 'Link', 'Unlink' ]
            versionCheck: false
            autoParagraph: false
            extraPlugins:
                - 'justify'
        app_custom_half_height_config:
            height: '100px'
            toolbar:
                - [ 'Bold', 'Italic', 'Underline', 'Strikethrough', 'Subscript', 'Superscript', '-', 'BulletedList', 'NumberedList', '-',  'Indent', 'Outdent', '-', 'Link', 'Unlink' ]
            versionCheck: false
            autoParagraph: false
    plugins:
        justify:
            path:     '/build/ckeditor/plugins/justify/'
            filename: 'plugin.js'
